### ISSUE TITLE
Error when generating the frontend component 

### ISSUE THREAD

**Issue by TikhomirovME** [Haulmont/jmix-frontend#271]
Steps :

    Two related objects City and Organization (with the city field)

    Creating an interface component for a city (all default settings)

    Creating a frontend component for an Organization. In the fronten component editor, I create a custom fetch-plan in which I select fields for both entity.

    I select the sfetch-plan I just created for both screens.

    I click Ok.

Expected result:

run front generator
Actual result:

Error running front generator

Skipping project model prompts since model is provided Skipping prompts since answers are provided events.js:292 throw er;
```
// Unhandled 'error' event ^ TypeError: Cannot read property 'allProperties' of undefined at Object.exports.deriveViewBasedBrowserTemplateModel (/Users/a18858318/IdeaProjects/jmix/frontsample/frontend/generation/node_modules/@haulmont/jmix-front-generator/lib/building-blocks/stages/template-model/pieces/entity-browser/browser.js:13:74) at /Users/a18858318/IdeaProjects/jmix/frontsample/frontend/generation/node_modules/@haulmont/jmix-front-generator/lib/generators/react-typescript/entity-management/template-model.js:18:201 at Generator.next ( ) at /Users/a18858318/IdeaProjects/jmix/frontsample/frontend/generation/node_modules/@haulmont/jmix-front-generator/lib/generators/react-typescript/entity-management/template-model.js:8:71 at new Promise ( ) at __awaiter (/Users/a18858318/IdeaProjects/jmix/frontsample/frontend/generation/node_modules/@haulmont/jmix-front-generator/lib/generators/react-typescript/entity-management/template-model.js:4:12) at exports.deriveTemplateModel (/Users/a18858318/IdeaProjects/jmix/frontsample/frontend/generation/node_modules/@haulmont/jmix-front-generator/lib/generators/react-typescript/entity-management/template-model.js:17:72) at Object. (/Users/a18858318/IdeaProjects/jmix/frontsample/frontend/generation/node_modules/@haulmont/jmix-front-generator/lib/building-blocks/pipelines/defaultPipeline.js:42:37) at Generator.next ( ) at fulfilled (/Users/a18858318/IdeaProjects/jmix/frontsample/frontend/generation/node_modules/@haulmont/jmix-front-generator/lib/building-blocks/pipelines/defaultPipeline.js:5:58) Emitted 'error' event on ReactEntityManagementGenerator instance at: at Immediate. (/Users/a18858318/IdeaProjects/jmix/frontsample/frontend/generation/node_modules/yeoman-generator/lib/index.js:1022:20) at processImmediate (internal/timers.js:456:21)

[frontsample(2).zip](https://github.com/Haulmont/jmix-frontend/files/6440138/frontsample.2.zip)

```

**Comment by web-devel** [comment]
Hi @TikhomirovME, what version of `@haulmont/jmix-front-generator` is used? Run the following command in the `frontend` directory of your project:
```
npx gen-jmix-front -v
```
