### ISSUE TITLE
SDK generation fails due to a breaking change in typescript

### ISSUE THREAD

**Issue by owlet1997** [Haulmont/jmix-frontend#774]
**Environment:**
OS Ubuntu 20.04 LTS
npm 7.24
Jmix version: 1.2.0-SNAPSHOT
Jmix Studio plugin version: 1.1.SNAPSHOT3782-212
IntelliJ version: IntelliJ IDEA 2021.2.3 (Ultimate Edition)

**TC:**
1. Open [attached](https://app.zenhub.com/files/318761614/f68b6528-a166-49b8-a7f9-c543f9095010/download) project -> Create new frontend module with custom generator version 2.0.0-next.6

**AR:**
error running frontend generator
```
Skipping project model prompts since model is provided Skipping prompts since answers are provided 
Generating to /home/shatalova/IdeaProjects/fr110/frontend Generating to /home/shatalova/IdeaProjects/fr110/frontend 
Generate SDK model and services to src/jmix 
Unhandled Rejection Promise {   SyntaxError: Identifier expected. (1:19) > 1 | import { Item as } from "./f_Item"; | ^ 2 | 
export class AssocEntity { 3 | static NAME = "f_AssocEntity"; 4 | id?: string; at t 
(/home/shatalova/IdeaProjects/fr110/frontend/generation/node_modules/prettier/parser-typescript.js:1:285) at Object.parse 
(/home/shatalova/IdeaProjects/fr110/frontend/generation/node_modules/prettier/parser-typescript.js:14:180461) at 
Object.parse (/home/shatalova/IdeaProjects/fr110/frontend/generation/node_modules/prettier/index.js:9739:19) at 
coreFormat (/home/shatalova/IdeaProjects/fr110/frontend/generation/node_modules/prettier/index.js:13252:23) at format 
(/home/shatalova/IdeaProjects/fr110/frontend/generation/node_modules/prettier/index.js:13510:73) at formatWithCursor 
(/home/shatalova/IdeaProjects/fr110/frontend/generation/node_modules/prettier/index.js:13526:12) at 
/home/shatalova/IdeaProjects/fr110/frontend/generation/node_modules/prettier/index.js:44207:15 at Object.format 
(/home/shatalova/IdeaProjects/fr110/frontend/generation/node_modules/prettier/index.js:44226:12) at 
DestroyableTransform._transform 
(/home/shatalova/IdeaProjects/fr110/frontend/generation/node_modules/@haulmont/jmix-front-generator/lib/building-
blocks/stages/configuring/defaultConfigureGenerator.js:47:50) at DestroyableTransform.Transform._read 
(/home/shatalova/IdeaProjects/fr110/frontend/generation/node_modules/through2/node_modules/readable-
stream/lib/_stream_transform.js:184:10) { loc: { start: [Object] }, codeFrame: '> 1 | import { Item as } from "./f_Item";\n' + ' | 
^\n' + ' 2 | export class AssocEntity {\n' + ' 3 | static NAME = "f_AssocEntity";\n' + ' 4 | id?: string;' } } reason: SyntaxError: 
Identifier expected. (1:19) > 1 | import { Item as } from "./f_Item"; | ^ 2 | export class AssocEntity { 3 | static NAME = 
"f_AssocEntity"; 4 | id?: string; at t (/home/shatalova/IdeaProjects/fr110/frontend/generation/node_modules/prettier/parser-
typescript.js:1:285) at Object.parse 
(/home/shatalova/IdeaProjects/fr110/frontend/generation/node_modules/prettier/parser-typescript.js:14:180461) at 
Object.parse (/home/shatalova/IdeaProjects/fr110/frontend/generation/node_modules/prettier/index.js:9739:19) at 
coreFormat (/home/shatalova/IdeaProjects/fr110/frontend/generation/node_modules/prettier/index.js:13252:23) at format 
(/home/shatalova/IdeaProjects/fr110/frontend/generation/node_modules/prettier/index.js:13510:73) at formatWithCursor 
(/home/shatalova/IdeaProjects/fr110/frontend/generation/node_modules/prettier/index.js:13526:12) at 
/home/shatalova/IdeaProjects/fr110/frontend/generation/node_modules/prettier/index.js:44207:15 at Object.format 
(/home/shatalova/IdeaProjects/fr110/frontend/generation/node_modules/prettier/index.js:44226:12) at 
DestroyableTransform._transform 
(/home/shatalova/IdeaProjects/fr110/frontend/generation/node_modules/@haulmont/jmix-front-generator/lib/building-
blocks/stages/configuring/defaultConfigureGenerator.js:47:50) at DestroyableTransform.Transform._read 
(/home/shatalova/IdeaProjects/fr110/frontend/generation/node_modules/through2/node_modules/readable-
stream/lib/_stream_transform.js:184:10) { loc: { start: { line: 1, column: 19 } }, codeFrame: '> 1 | import { Item as } from 
"./f_Item";\n' + ' | ^\n' + ' 2 | export class AssocEntity {\n' + ' 3 | static NAME = "f_AssocEntity";\n' + ' 4 | id?: string;' }

```

**Comment by vyacheslav-pushkin** [comment]
Fixed in 2.0.0-next.7

**Comment by owlet1997** [comment]
**TC:**
1. Open [attached](https://app.zenhub.com/files/318761614/f68b6528-a166-49b8-a7f9-c543f9095010/download) project -> Create new frontend module with custom generator version 2.0.0-next.7
2. Create new frontend component `Entity management` for RecursEntity -> (Optionally) Choose `assoc` attribute in the GraphQL query editor -> Finish

**AR:**
Error running frontend generator, component has not been created
Error log:
```
Skipping project model prompts since model is provided Generating to /home/shatalova/IdeaProjects/fr110/frontend/src/jmix Generating sdk:Model to /home/shatalova/IdeaProjects/fr110/frontend/src/jmix Unhandled Rejection Promise {   SyntaxError: Type expected. (9:38) 7 | entityEntry?: any | null; 8 | } > 9 | export type KeyValueEntityViewName = ; | ^ 10 | export type KeyValueEntityView = never; 11 | at t (/home/shatalova/IdeaProjects/fr110/frontend/generation/node_modules/prettier/parser-typescript.js:1:285) at Object.parse (/home/shatalova/IdeaProjects/fr110/frontend/generation/node_modules/prettier/parser-typescript.js:14:180461) at Object.parse (/home/shatalova/IdeaProjects/fr110/frontend/generation/node_modules/prettier/index.js:9739:19) at coreFormat (/home/shatalova/IdeaProjects/fr110/frontend/generation/node_modules/prettier/index.js:13252:23) at format (/home/shatalova/IdeaProjects/fr110/frontend/generation/node_modules/prettier/index.js:13510:73) at formatWithCursor (/home/shatalova/IdeaProjects/fr110/frontend/generation/node_modules/prettier/index.js:13526:12) at /home/shatalova/IdeaProjects/fr110/frontend/generation/node_modules/prettier/index.js:44207:15 at Object.format (/home/shatalova/IdeaProjects/fr110/frontend/generation/node_modules/prettier/index.js:44226:12) at DestroyableTransform._transform (/home/shatalova/IdeaProjects/fr110/frontend/generation/node_modules/@haulmont/jmix-front-generator/lib/building-blocks/stages/configuring/defaultConfigureGenerator.js:47:50) at DestroyableTransform.Transform._read (/home/shatalova/IdeaProjects/fr110/frontend/generation/node_modules/readable-stream/lib/_stream_transform.js:184:10) at DestroyableTransform.Transform._write (/home/shatalova/IdeaProjects/fr110/frontend/generation/node_modules/readable-stream/lib/_stream_transform.js:172:83) at doWrite (/home/shatalova/IdeaProjects/fr110/frontend/generation/node_modules/readable-stream/lib/_stream_writable.js:428:64) at writeOrBuffer (/home/shatalova/IdeaProjects/fr110/frontend/generation/node_modules/readable-stream/lib/_stream_writable.js:417:5) at DestroyableTransform.Writable.write (/home/shatalova/IdeaProjects/fr110/frontend/generation/node_modules/readable-stream/lib/_stream_writable.js:334:11) at PTransform.ondata (internal/streams/readable.js:731:22) at PTransform.emit (events.js:400:28) { loc: { start: [Object] }, codeFrame: ' 7 | entityEntry?: any | null;\n' + ' 8 | }\n' + '> 9 | export type KeyValueEntityViewName = ;\n' + ' | ^\n' + ' 10 | export type KeyValueEntityView = never;\n' + ' 11 | ' } } reason: SyntaxError: Type expected. (9:38) 7 | entityEntry?: any | null; 8 | } > 9 | export type KeyValueEntityViewName = ; | ^ 10 | export type KeyValueEntityView = never; 11 | at t (/home/shatalova/IdeaProjects/fr110/frontend/generation/node_modules/prettier/parser-typescript.js:1:285) at Object.parse (/home/shatalova/IdeaProjects/fr110/frontend/generation/node_modules/prettier/parser-typescript.js:14:180461) at Object.parse (/home/shatalova/IdeaProjects/fr110/frontend/generation/node_modules/prettier/index.js:9739:19) at coreFormat (/home/shatalova/IdeaProjects/fr110/frontend/generation/node_modules/prettier/index.js:13252:23) at format (/home/shatalova/IdeaProjects/fr110/frontend/generation/node_modules/prettier/index.js:13510:73) at formatWithCursor (/home/shatalova/IdeaProjects/fr110/frontend/generation/node_modules/prettier/index.js:13526:12) at /home/shatalova/IdeaProjects/fr110/frontend/generation/node_modules/prettier/index.js:44207:15 at Object.format (/home/shatalova/IdeaProjects/fr110/frontend/generation/node_modules/prettier/index.js:44226:12) at DestroyableTransform._transform (/home/shatalova/IdeaProjects/fr110/frontend/generation/node_modules/@haulmont/jmix-front-generator/lib/building-blocks/stages/configuring/defaultConfigureGenerator.js:47:50) at DestroyableTransform.Transform._read (/home/shatalova/IdeaProjects/fr110/frontend/generation/node_modules/readable-stream/lib/_stream_transform.js:184:10) at DestroyableTransform.Transform._write (/home/shatalova/IdeaProjects/fr110/frontend/generation/node_modules/readable-stream/lib/_stream_transform.js:172:83) at doWrite (/home/shatalova/IdeaProjects/fr110/frontend/generation/node_modules/readable-stream/lib/_stream_writable.js:428:64) at writeOrBuffer (/home/shatalova/IdeaProjects/fr110/frontend/generation/node_modules/readable-stream/lib/_stream_writable.js:417:5) at DestroyableTransform.Writable.write (/home/shatalova/IdeaProjects/fr110/frontend/generation/node_modules/readable-stream/lib/_stream_writable.js:334:11) at PTransform.ondata (internal/streams/readable.js:731:22) at PTransform.emit (events.js:400:28) { loc: { start: { line: 9, column: 38 } }, codeFrame: ' 7 | entityEntry?: any | null;\n' + ' 8 | }\n' + '> 9 | export type KeyValueEntityViewName = ;\n' + ' | ^\n' + ' 10 | export type KeyValueEntityView = never;\n' + ' 11 | ' }
```

**Comment by owlet1997** [comment]
**TC:**

Open attached project -> Create new frontend module with custom generator version 2.0.0-next.7

**AR:**
error running frontend generator:
```
Skipping project model prompts since model is provided Skipping prompts since answers are provided Generating to /home/shatalova/IdeaProjects/front1/frontend Generating to /home/shatalova/IdeaProjects/front1/frontend Generate SDK model and services to src/jmix Unhandled Rejection Promise {   SyntaxError: Type expected. (9:38) 7 | entityEntry?: any | null; 8 | } > 9 | export type KeyValueEntityViewName = ; | ^ 10 | export type KeyValueEntityView = never; 11 | at t (/home/shatalova/IdeaProjects/front1/frontend/generation/node_modules/prettier/parser-typescript.js:1:285) at Object.parse (/home/shatalova/IdeaProjects/front1/frontend/generation/node_modules/prettier/parser-typescript.js:14:180461) at Object.parse (/home/shatalova/IdeaProjects/front1/frontend/generation/node_modules/prettier/index.js:9739:19) at coreFormat (/home/shatalova/IdeaProjects/front1/frontend/generation/node_modules/prettier/index.js:13252:23) at format (/home/shatalova/IdeaProjects/front1/frontend/generation/node_modules/prettier/index.js:13510:73) at formatWithCursor (/home/shatalova/IdeaProjects/front1/frontend/generation/node_modules/prettier/index.js:13526:12) at /home/shatalova/IdeaProjects/front1/frontend/generation/node_modules/prettier/index.js:44207:15 at Object.format (/home/shatalova/IdeaProjects/front1/frontend/generation/node_modules/prettier/index.js:44226:12) at DestroyableTransform._transform (/home/shatalova/IdeaProjects/front1/frontend/generation/node_modules/@haulmont/jmix-front-generator/lib/building-blocks/stages/configuring/defaultConfigureGenerator.js:47:50) at DestroyableTransform.Transform._read (/home/shatalova/IdeaProjects/front1/frontend/generation/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10) { loc: { start: [Object] }, codeFrame: ' 7 | entityEntry?: any | null;\n' + ' 8 | }\n' + '> 9 | export type KeyValueEntityViewName = ;\n' + ' | ^\n' + ' 10 | export type KeyValueEntityView = never;\n' + ' 11 | ' } } reason: SyntaxError: Type expected. (9:38) 7 | entityEntry?: any | null; 8 | } > 9 | export type KeyValueEntityViewName = ; | ^ 10 | export type KeyValueEntityView = never; 11 | at t (/home/shatalova/IdeaProjects/front1/frontend/generation/node_modules/prettier/parser-typescript.js:1:285) at Object.parse (/home/shatalova/IdeaProjects/front1/frontend/generation/node_modules/prettier/parser-typescript.js:14:180461) at Object.parse (/home/shatalova/IdeaProjects/front1/frontend/generation/node_modules/prettier/index.js:9739:19) at coreFormat (/home/shatalova/IdeaProjects/front1/frontend/generation/node_modules/prettier/index.js:13252:23) at format (/home/shatalova/IdeaProjects/front1/frontend/generation/node_modules/prettier/index.js:13510:73) at formatWithCursor (/home/shatalova/IdeaProjects/front1/frontend/generation/node_modules/prettier/index.js:13526:12) at /home/shatalova/IdeaProjects/front1/frontend/generation/node_modules/prettier/index.js:44207:15 at Object.format (/home/shatalova/IdeaProjects/front1/frontend/generation/node_modules/prettier/index.js:44226:12) at DestroyableTransform._transform (/home/shatalova/IdeaProjects/front1/frontend/generation/node_modules/@haulmont/jmix-front-generator/lib/building-blocks/stages/configuring/defaultConfigureGenerator.js:47:50) at DestroyableTransform.Transform._read (/home/shatalova/IdeaProjects/front1/frontend/generation/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10) { loc: { start: { line: 9, column: 38 } }, codeFrame: ' 7 | entityEntry?: any | null;\n' + ' 8 | }\n' + '> 9 | export type KeyValueEntityViewName = ;\n' + ' | ^\n' + ' 10 | export type KeyValueEntityView = never;\n' + ' 11 | ' }
```

[front1.zip](https://github.com/Haulmont/jmix-frontend/files/7580999/front1.zip)

**Comment by vyacheslav-pushkin** [comment]
@owlet1997 This is a Studio problem that was fixed today.
