### ISSUE TITLE
Error creating frontend module

### ISSUE THREAD

**Issue by alexbudarov** [Haulmont/jmix-frontend#784]
NPM 8.1.0
NodeJS 16.13.0
Jmix plugin - master snapshot 1.1.SNAPSHOT3792-212

Jmix project attached:
[cars.zip](https://github.com/Haulmont/jmix-frontend/files/7582652/cars.zip)

Create Frontend Module from tool window.
The following error appears (after successful listGenerators):

![image](https://user-images.githubusercontent.com/6158807/142897015-20f1686c-1bf6-463e-a906-6fd7db36ebf0.png)

Skipping project model prompts since model is provided Skipping prompts since answers are provided Generating to /home/alexander/projects/jjunk/untitled/frontend Generating to /home/alexander/projects/jjunk/untitled/frontend Generate SDK model and services to src/jmix force ../../package.json create ../i18n/en.json create ../../public/favicon.ico create ../../public/index.html create ../../public/manifest.json create ../config.ts create ../index.css create ../index.tsx create ../react-app-env.d.ts create ../registerServiceWorker.ts create ../routing.ts create ../app/App.css create ../app/App.test.tsx create ../app/App.tsx create ../app/AppMenu.tsx create ../app/CenteredLoader.css create ../app/CenteredLoader.tsx create ../dev/hooks.ts create ../dev/palette.tsx create ../dev/previews.tsx create ../i18n/LanguageSwitcher.css create ../i18n/LanguageSwitcher.tsx create ../i18n/i18nMappings.ts create ../i18n/localeCaptions.ts create ../app/common/Centered.css create ../app/common/Centered.tsx create ../app/header/AppHeader.css create ../app/header/AppHeader.tsx create ../app/home/HomePage.tsx create ../app/icons/JmixDarkIcon.tsx create ../app/icons/JmixLightIcon.tsx create ../app/login/Login.css create ../app/login/Login.tsx create ../../README.md create ../../images.d.ts create ../../package-lock.json create ../../tsconfig.json create ../../tsconfig.prod.json create ../../tsconfig.test.json create ../../tslint.json create ../../.env.production.local create ../../.env.development.local create ../../.gitignore create ../../.editorconfig /home/alexander/projects/jjunk/untitled/frontend/generation/node_modules/prettier/index.js:9750 throw error; ^ SyntaxError: Identifier expected. (1:20) > 1 | import { Model as } from "./Model"; | ^ 2 | export class Car { 3 | static NAME = "Car"; 4 | id?: string; at t (/home/alexander/projects/jjunk/untitled/frontend/generation/node_modules/prettier/parser-typescript.js:1:285) at Object.parse (/home/alexander/projects/jjunk/untitled/frontend/generation/node_modules/prettier/parser-typescript.js:14:180461) at Object.parse (/home/alexander/projects/jjunk/untitled/frontend/generation/node_modules/prettier/index.js:9739:19) at coreFormat (/home/alexander/projects/jjunk/untitled/frontend/generation/node_modules/prettier/index.js:13252:23) at format (/home/alexander/projects/jjunk/untitled/frontend/generation/node_modules/prettier/index.js:13510:73) at formatWithCursor (/home/alexander/projects/jjunk/untitled/frontend/generation/node_modules/prettier/index.js:13526:12) at /home/alexander/projects/jjunk/untitled/frontend/generation/node_modules/prettier/index.js:44207:15 at Object.format (/home/alexander/projects/jjunk/untitled/frontend/generation/node_modules/prettier/index.js:44226:12) at DestroyableTransform._transform (/home/alexander/projects/jjunk/untitled/frontend/generation/node_modules/@haulmont/jmix-front-generator/lib/building-blocks/stages/configuring/defaultConfigureGenerator.js:48:50) at DestroyableTransform.Transform._read (/home/alexander/projects/jjunk/untitled/frontend/generation/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10) { loc: { start: { line: 1, column: 20 } }, codeFrame: '> 1 | import { Model as } from "./Model";\n' + ' | ^\n' + ' 2 | export class Car {\n' + ' 3 | static NAME = "Car";\n' + ' 4 | id?: string;' }

**Comment by alexbudarov** [comment]
Works fine with generator version 2.0.0-next.7
