### ISSUE TITLE
Error creating frontend component in Jmix project

### ISSUE THREAD

**Issue by alexbudarov** [Haulmont/jmix-frontend#785]
Jmix plugin: master snapshot 1.1.SNAPSHOT3792-212
NPM: 8.1.0
nodejs: 16.13.0

Project: https://github.com/jmix-projects/user-management

- open project
- new -> Frontend Component -> Entity Browser -> choose User entity -> Finish

Error occurs:

Skipping project model prompts since model is provided Generating to /home/alexander/projects/jsamples/user-management-new/frontend/src/jmix Generating sdk:Model to /home/alexander/projects/jsamples/user-management-new/frontend/src/jmix Unhandled Rejection Promise {   SyntaxError: Type expected. (9:38) 7 | entityEntry?: any | null; 8 | } > 9 | export type KeyValueEntityViewName = ; | ^ 10 | export type KeyValueEntityView = never; 11 | at t (/home/alexander/projects/jsamples/user-management-new/frontend/generation/node_modules/prettier/parser-typescript.js:1:285) at Object.parse (/home/alexander/projects/jsamples/user-management-new/frontend/generation/node_modules/prettier/parser-typescript.js:14:180461) at Object.parse (/home/alexander/projects/jsamples/user-management-new/frontend/generation/node_modules/prettier/index.js:9739:19) at coreFormat (/home/alexander/projects/jsamples/user-management-new/frontend/generation/node_modules/prettier/index.js:13252:23) at format (/home/alexander/projects/jsamples/user-management-new/frontend/generation/node_modules/prettier/index.js:13510:73) at formatWithCursor (/home/alexander/projects/jsamples/user-management-new/frontend/generation/node_modules/prettier/index.js:13526:12) at /home/alexander/projects/jsamples/user-management-new/frontend/generation/node_modules/prettier/index.js:44207:15 at Object.format (/home/alexander/projects/jsamples/user-management-new/frontend/generation/node_modules/prettier/index.js:44226:12) at DestroyableTransform._transform (/home/alexander/projects/jsamples/user-management-new/frontend/generation/node_modules/@haulmont/jmix-front-generator/lib/building-blocks/stages/configuring/defaultConfigureGenerator.js:47:50) at DestroyableTransform.Transform._read (/home/alexander/projects/jsamples/user-management-new/frontend/generation/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10) at DestroyableTransform.Transform._write (/home/alexander/projects/jsamples/user-management-new/frontend/generation/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:83) at doWrite (/home/alexander/projects/jsamples/user-management-new/frontend/generation/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:428:64) at writeOrBuffer (/home/alexander/projects/jsamples/user-management-new/frontend/generation/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:417:5) at DestroyableTransform.Writable.write (/home/alexander/projects/jsamples/user-management-new/frontend/generation/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:334:11) at PTransform.ondata (node:internal/streams/readable:754:22) at PTransform.emit (node:events:390:28) { loc: { start: [Object] }, codeFrame: ' 7 | entityEntry?: any | null;\n' + ' 8 | }\n' + '> 9 | export type KeyValueEntityViewName = ;\n' + ' | ^\n' + ' 10 | export type KeyValueEntityView = never;\n' + ' 11 | ' } } reason: SyntaxError: Type expected. (9:38) 7 | entityEntry?: any | null; 8 | } > 9 | export type KeyValueEntityViewName = ; | ^ 10 | export type KeyValueEntityView = never; 11 | at t (/home/alexander/projects/jsamples/user-management-new/frontend/generation/node_modules/prettier/parser-typescript.js:1:285) at Object.parse (/home/alexander/projects/jsamples/user-management-new/frontend/generation/node_modules/prettier/parser-typescript.js:14:180461) at Object.parse (/home/alexander/projects/jsamples/user-management-new/frontend/generation/node_modules/prettier/index.js:9739:19) at coreFormat (/home/alexander/projects/jsamples/user-management-new/frontend/generation/node_modules/prettier/index.js:13252:23) at format (/home/alexander/projects/jsamples/user-management-new/frontend/generation/node_modules/prettier/index.js:13510:73) at formatWithCursor (/home/alexander/projects/jsamples/user-management-new/frontend/generation/node_modules/prettier/index.js:13526:12) at /home/alexander/projects/jsamples/user-management-new/frontend/generation/node_modules/prettier/index.js:44207:15 at Object.format (/home/alexander/projects/jsamples/user-management-new/frontend/generation/node_modules/prettier/index.js:44226:12) at DestroyableTransform._transform (/home/alexander/projects/jsamples/user-management-new/frontend/generation/node_modules/@haulmont/jmix-front-generator/lib/building-blocks/stages/configuring/defaultConfigureGenerator.js:47:50) at DestroyableTransform.Transform._read (/home/alexander/projects/jsamples/user-management-new/frontend/generation/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10) at DestroyableTransform.Transform._write (/home/alexander/projects/jsamples/user-management-new/frontend/generation/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:83) at doWrite (/home/alexander/projects/jsamples/user-management-new/frontend/generation/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:428:64) at writeOrBuffer (/home/alexander/projects/jsamples/user-management-new/frontend/generation/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:417:5) at DestroyableTransform.Writable.write (/home/alexander/projects/jsamples/user-management-new/frontend/generation/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:334:11) at PTransform.ondata (node:internal/streams/readable:754:22) at PTransform.emit (node:events:390:28) { loc: { start: { line: 9, column: 38 } }, codeFrame: ' 7 | entityEntry?: any | null;\n' + ' 8 | }\n' + '> 9 | export type KeyValueEntityViewName = ;\n' + ' | ^\n' + ' 10 | export type KeyValueEntityView = never;\n' + ' 11 | ' }

**Comment by alexbudarov** [comment]
Works fine with generator 2.0.0-next.7
