### ISSUE TITLE
Error: Can't serialize value: Expected type 'Date' but was 'Timestamp'

### ISSUE THREAD

**Issue by owlet1997** [Haulmont/jmix-frontend#957]
**Environment:**
Platform V version: 1.1.2
Platform V Studio plugin version: 1.2.2.2-SNAPSHOT.10-213
IntelliJ version: IntelliJ IDEA 2021.3.2 (Ultimate Edition)
frontend generator v.3.2.0-next.2

**TC:**
1. Ask QA about the test project, it couldn't be attached here because of too large size
2. Start the server app -> Start the React app -> Login as admin
3. Open the Hello Entity List -> Create new one -> Fill the DateTime field and save

**AR:**
Failed to perform the requested operation.
``` 
index.js:1 Error: Can't serialize value (/HelloEntityList[2]/dateTime) : Expected type 'Date' but was 'Timestamp'.
    at new ApolloError (index.ts:58:1)
    at useQuery (useQuery.ts:301:1)
    at useLazyQuery (useLazyQuery.ts:34:1)
    at useEntityListData (index.esm.js:9993:1)
    at useEntityList (index.esm.js:951:1)
    at HelloEntityList.tsx:66:1
    at observer.ts:57:1
    at useObserver.ts:115:1
    at trackDerivedFunction (derivation.ts:179:1)
    at Reaction.track (reaction.ts:137:1)
    at useObserver (useObserver.ts:113:1)
    at wrappedComponent (observer.ts:57:1)
    at renderWithHooks (react-dom.development.js:14985:1)
    at updateFunctionComponent (react-dom.development.js:17356:1)
    at updateSimpleMemoComponent (react-dom.development.js:17215:1)
    at beginWork (react-dom.development.js:19140:1)
    at beginWork$1 (react-dom.development.js:23940:1)
    at performUnitOfWork (react-dom.development.js:22776:1)
    at workLoopSync (react-dom.development.js:22707:1)
    at renderRootSync (react-dom.development.js:22670:1)
    at performSyncWorkOnRoot (react-dom.development.js:22293:1)
    at react-dom.development.js:11327:1
    at unstable_runWithPriority (scheduler.development.js:468:1)
    at runWithPriority$1 (react-dom.development.js:11276:1)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11322:1)
    at flushSyncCallbackQueue (react-dom.development.js:11309:1)
    at scheduleUpdateOnFiber (react-dom.development.js:21893:1)
    at dispatchAction (react-dom.development.js:16139:1)
    at Object.onNext [as next] (useQuery.ts:176:1)
    at notifySubscription (module.js:132:1)
    at onNotify (module.js:176:1)
    at SubscriptionObserver.next (module.js:225:1)
    at iteration.ts:13:1
    at Array.forEach (<anonymous>)
    at iterateObserversSafely (iteration.ts:13:1)
    at ObservableQuery.reportResult (ObservableQuery.ts:766:1)
    at Object.next (ObservableQuery.ts:721:1)
    at iteration.ts:13:1
    at Array.forEach (<anonymous>)
    at iterateObserversSafely (iteration.ts:13:1)
    at Object.next (Concast.ts:171:1)
    at notifySubscription (module.js:132:1)
    at onNotify (module.js:176:1)
    at SubscriptionObserver.next (module.js:225:1)
    at asyncMap.ts:34:1
```
**ER:**
a table with instances is displayed as usual

**Comment by SvyatovetsD** [comment]
Seems like a hibernate issue. Will be addressed to the backend team

**Comment by zaharchenko-evgeny** [comment]
fixed in hibernate addon
